version: '3.2'
services:
    aem65-author:
        image: jmc22071983/aem6.5-author
        ports:
            - '4502:4502'
            - '8000:8000'
        environment:  
           RUNMODE: "${RUNMODE}"
        volumes:
            - 'C:/aem65-author-volume:/crx-quickstart/logs'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.hostname == docker-desktop
        networks:
            - network
    aem65-publish:
            image: jmc22071983/aem6.5-publish
        ports:
            - '4503:4503'
            - '8001:8001'
        environment:  
           RUNMODE: "${RUNMODE}"
        volumes:
            - 'C:/aem65-publish-volume:/crx-quickstart/logs'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.hostname == docker-desktop
        networks:
            - network
    apache-dispatcher:
        image: jmc22071983/dispatcher
        depends_on:
            - aem65-publish
        ports:
            - '80:80'
            - '443:443'
        environment:  
            AEM_HOST: 'aem65-publish'
            AEM_PORT: '4503'
        volumes:
            - 'C:/aem-dispatcher-volume:/etc/httpd/dispatcher_cache'
            - 'C:/aem-dispatcher-volume:/etc/httpd/logs'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.hostname == docker-desktop
        networks:
            - network
volumes:
    aem65-author-volume:
    aem65-publish-volume:
    aem-dispatcher-volume:
networks:
    network:
        driver: overlay
