version: '3.2'
services:
    aem65-author:
        image: jmc22071983/aem6.5-author:0.0.1
        ports:
            - '4502:4502'
            - '8000:8000'
        environment:  
           RUNMODE: "${RUNMODEAUT}"
        volumes:
            - 'C:/AEM/Docker/author:/crx-quickstart/logs'
            - 'author-repository:/crx-quickstart/repository'
        deploy:
            replicas: 1
        networks:
            - network
    aem65-publish:
        image: jmc22071983/aem6.5-publish:0.0.1
        ports:
            - '4503:4503'
            - '8001:8001'
        environment:  
           RUNMODE: "${RUNMODEPUB}"
        volumes:
            - 'C:/AEM/Docker/publish:/crx-quickstart/logs'
            - 'publish-repository:/crx-quickstart/repository'
        deploy:
            replicas: 1
        networks:
            - network
volumes:
    author:
    author-repository:
    publish:
    publish-repository:
networks:
    network:
        driver: overlay