version: '3'
services:
    aem632-publish:
        image: jmc22071983/aem632-publish:0.0.3-SNAPSHOT
        ports:
            - '4503:4503'
            - '8001:8001'
        environment:  
           RUNMODE: 'local'
        volumes:
            - 'aem632-publish:/crx-quickstart/repository'
        networks:
            - network
    apache-dispatcher:
        image: jmc22071983/dispatcher:0.0.1
        depends_on:
            - aem632-publish
        ports:
            - '80:80'
            - '443:443'
        environment:  
            AEM_HOST: 'aem632-publish'
            AEM_PORT: '4503'
        volumes:
            - 'aem-dispatcher:/etc/httpd/dispatcher_cache'
        networks:
            - network 
volumes:
    aem632-publish:
    aem-dispatcher:
networks:
    network:
        driver: overlay