version: '3.2'
services:
    aem65-author:
        image: jmc22071983/aem6.5-author:0.0.1
        ports:
            - '4502:4502'
            - '8000:8000'
        environment:  
           RUNMODE: "${RUNMODEAUT}"
        volumes:
            - '/mnt/sda1/aem65-author-volume:/crx-quickstart/logs'
            - '/mnt/sda1/aem/aem65-author-repository:/crx-quickstart/repository'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.hostname == manager
        networks:
            - network
    aem65-publish:
        image: jmc22071983/aem6.5-publish:0.0.1
        ports:
            - '4503:4503'
            - '8001:8001'
        environment:  
           RUNMODE: "${RUNMODEPUB}"
        volumes:
            - '/mnt/sda1/aem65-publish-volume:/crx-quickstart/logs'
             - 'aem65-publish-repository:/crx-quickstart/repository'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.hostname == manager
        networks:
            - network
    apache-dispatcher:
        image: jmc22071983/dispatcher:0.0.1
        depends_on:
            - aem65-publish
        ports:
            - '80:80'
            - '443:443'
        environment:  
            AEM_HOST: 'aem65-publish'
            AEM_PORT: '4503'
        volumes:
            - '/mnt/sda1/aem-dispatcher-volume:/etc/httpd/dispatcher_cache'
            - '/mnt/sda1/aem-dispatcher-volume:/etc/httpd/logs'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.hostname == manager
        networks:
            - network
volumes:
    aem65-author-volume:
    aem65-publish-volume:
    aem-dispatcher-volume:
    aem65-author-repository:
    aem65-publish-repository:
networks:
    network:
        driver: overlay