version: '3'
services:
    aem632-author:
        image: jmc22071983/aem632-author:0.0.4-SNAPSHOT
        ports:
            - '4502:4502'
            - '8000:8000'
        volumes:
            - 'aem632-author:/crx-quickstart/repository'
            - '/aem632-author/logs:/crx-quickstart/logs'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.role == worker
        networks:
            - network
    aem632-publish:
        image: jmc22071983/aem632-publish:0.0.2-SNAPSHOT
        ports:
            - '4503:4503'
            - '8001:8001'
        volumes:
            - 'aem632-publish:/crx-quickstart/repository'
            - '/aem632-publish/logs:/crx-quickstart/logs'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.role == worker
        networks:
            - network
    apache-dispatcher:
        image: jmc22071983/dispatcher:0.0.1
        depends_on:
            - aem632-publish
        ports:
            - '80:80'
            - '443:443'
        environment:  
            AEM_HOST: 'aem632-publish'
            AEM_PORT: '4503'
        volumes:
            - '/aem-dispatcher/logs:/etc/httpd/logs'
            - '/aem-dispatcher/dispatcher_cache:/etc/httpd/dispatcher_cache'
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.role == worker
        networks:
            - network 
volumes:
    aem632-author:
    aem632-publish:
networks:
    network:
        driver: overlay