version: '3'
services:
    aem632-author:
        image: jmc22071983/aem632-author:0.0.4-SNAPSHOT
        ports:
            - '4502:4502'
            - '8000:8000'
        volumes:
            - 'aem632-author:/crx-quickstart/repository'
        deploy:
            mode: replicated
            replicas: 1
        networks:
            - network
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.hostname == aem1
volumes:
    aem632-author:
    aem632-publish:
networks:
    network:
        driver: overlay